begin;
insert into public.departments(code,name) values ('OP','Office of the President'),('OSG','Office of the Secretary General'),('OCFO','Office of the Chief Financial Officer'),('ACADS','Academics'),('CREA','Creatives'),('ExRel','External Relations'),('HR','Human Resources'),('RND','Research and Development') on conflict(code) do nothing;
insert into public.request_types(code,name,creates_commitment) values ('BUDGET_REQUEST','Budget request',false),('BUDGET_CHANGE','Budget change',false),('DISBURSEMENT_ACCREDITED','Accredited disbursement',true),('DISBURSEMENT_UNACCREDITED','Unaccredited disbursement',true),('REIMBURSEMENT','Reimbursement',true),('BUDGET_TRANSFER','Budget transfer / inter-unit charging',true),('PROJECT_END_REVENUE','Project-end / revenue submission',false) on conflict(code) do nothing;
insert into public.document_requirements(request_type_id,document_code,label,display_order,condition_type,condition_json)
select t.id,v.code,v.label,v.n,v.condition,case when v.condition='AMOUNT_LT' then '{"amount":15000}'::jsonb else null end
from public.request_types t cross join (values
 ('BUDGET_REQUEST','LETTER','Budget Request Letter',1,null),('BUDGET_REQUEST','BREAKDOWN','Budget Breakdown',2,null),
 ('BUDGET_CHANGE','LETTER','Budget Change Letter',1,null),('BUDGET_CHANGE','BREAKDOWN','Budget Breakdown',2,null),
 ('DISBURSEMENT_ACCREDITED','PPF','Project Proposal Form (PPF)',1,null),('DISBURSEMENT_ACCREDITED','INVOICE','Invoice',2,null),('DISBURSEMENT_ACCREDITED','PROOF','Proof of Purchase / Documentation',3,null),('DISBURSEMENT_ACCREDITED','PARTICIPANTS','List of Participants',4,null),('DISBURSEMENT_ACCREDITED','PDAF','PDAF',5,'AMOUNT_LT'),
 ('DISBURSEMENT_UNACCREDITED','PPF','Project Proposal Form (PPF)',1,null),('DISBURSEMENT_UNACCREDITED','INVOICE','Invoice',2,null),('DISBURSEMENT_UNACCREDITED','PROOF','Proof of Purchase / Documentation',3,null),('DISBURSEMENT_UNACCREDITED','PARTICIPANTS','List of Participants',4,null),('DISBURSEMENT_UNACCREDITED','PDAF','PDAF',5,'AMOUNT_LT'),('DISBURSEMENT_UNACCREDITED','ID','Valid ID',6,null),('DISBURSEMENT_UNACCREDITED','BANK','Bank Proof: name, account number, and bank name in one document',7,null),('DISBURSEMENT_UNACCREDITED','ADC','ADC Form',8,null),
 ('REIMBURSEMENT','PPF','Project Proposal Form (PPF)',1,null),('REIMBURSEMENT','INVOICE','Invoice',2,null),('REIMBURSEMENT','PROOF','Proof of Purchase / Documentation',3,null),('REIMBURSEMENT','PARTICIPANTS','List of Participants',4,null),('REIMBURSEMENT','PDAF','PDAF',5,'AMOUNT_LT'),('REIMBURSEMENT','ID','Valid ID',6,null),('REIMBURSEMENT','BANK','Bank Proof: name, account number, and bank name in one document',7,null),('REIMBURSEMENT','ADC','ADC Form',8,null),
 ('BUDGET_TRANSFER','LETTER','Budget Transfer Letter',1,null),('BUDGET_TRANSFER','SOA','Billing Statement / Statement of Account (SOA)',2,null),
 ('PROJECT_END_REVENUE','TURNOVER','Turnover Report',1,null),('PROJECT_END_REVENUE','VARIANCE','Variance Analysis Report',2,null),('PROJECT_END_REVENUE','REVENUE','Revenue/Budget Turnover',3,null)
) as v(type,code,label,n,condition) where t.code=v.type on conflict(request_type_id,document_code) do nothing;
insert into public.organization_settings(key,value) values
 ('allowed_email_domain','"student.ateneo.edu"'),('finance_notification_email','"aea.college.org@student.ateneo.edu"'),('google_drive_root_folder_id','"134YLUX7vHeA25cg5rXMzwZULIvZmyn_u"'),
 ('ocfo_can_record_transactions','false'),('allow_unlinked_transactions','false'),('report_due_days','7'),('reminder_days','3'),('unprocessed_warning_days','14'),('long_open_warning_days','30'),('notification_recipients','[]'),('workflow_overrides','{}') on conflict(key) do nothing;
insert into public.faq_guides(title,slug,content,display_order) select * from (values
 ('How do I submit a finance request?','submit','Prepare the required documents in a Google Drive folder. Share the folder with the finance integration account shown on the request form. Choose your department and request type, enter the minimum metadata, validate the folder, then submit. Your official copies and reference number will appear on the request detail page.',1),
 ('How are available funds calculated?','funds','Available funds = current approved department budget − actual expenses − active commitments. Revenue is tracked separately. Projects do not have independent budgets.',2),
 ('When is PDAF required?','pdaf','PDAF is required for accredited disbursement, unaccredited disbursement, and reimbursement when the amount is strictly below PHP 15,000. At PHP 15,000 or above, this conditional requirement does not apply.',3),
 ('How do revisions work?','revisions','When the CFO returns a request, edit its metadata and source folder, then resubmit. Previous official files, comments, approvals, and status history remain available. Internal OCFO comments are visible only to finance officers.',4)
) v(title,slug,content,display_order) where not exists(select 1 from public.faq_guides f where f.slug=v.slug and f.fiscal_year_id is null);
commit;
